

// Text constants
export const TEXT = {
  SIGN_IN: 'Sign in',
  EMAIL_PLACEHOLDER: 'Email Address',
  CONTINUE: 'Continue',
  ERROR_INVALID_EMAIL: 'Please enter a valid email address',
  ERROR_EMAIL_REQUIRED: 'Email is required',
  DONOT_HAVE_ACCOUNT: "Don’t have an Account?",
  CREATE_ONE: 'Create One',
  SENT_EMAIL: ' We Sent you an Email to reset your Password',
  RETURN_LOGIN: 'Return To Login',
  RESET: 'Reset',
  FORGOT_PASSWORD: 'Forgot Password?',
  ENTER_EMAIL:'Enter Email Address',
  CONTINUE_WITH_APPLE: 'Continue With Apple',
  CONTINUE_WITH_GOOGLE: 'Continue With Google',
  CONTINUE_WITH_FACEBOOK: 'Continue With Facebook',
  CREATE_ACCOUNT: 'Create Account',
  PASSWORD: 'Password',
  SEARCH: 'Search',
  CATEGORIES: 'Categories',
  TOP_SELLING: 'Top Selling',
  NEW_IN: 'New In',
  MEN: 'Men',
  WOMEN: 'Women',
  FINISH: 'Finish',
  ABOUT_YOURSELF: 'Tell us About yourself',
  SHOP_FOR: 'Who do you shop for?',
  OLD: 'How Old are you?',
  AGE_RANGE: 'Age Range',
  FIRST_NAME: 'Firstname',
  LAST_NAME: 'Lastname',
  SEE_ALL: 'See All',
  HOME_TAB: 'Home',
  NOTIFICATION_TAB: 'Notifications',
  RECEIPT_TAB: 'Receipt',
  PROFILE_TAB: 'Profile',
  FAVORITE_TAB: 'Favorites',
  PRODUCTS: 'Products',
  ADD_ADDRESS: 'Add Address',
  STREET_ADDRESS: 'Street Address',
  CITY: 'City',
  STATE: 'State',
  ZIP_CODE: 'Zip code',
  SAVE_BUTTON: 'Save',
  DONT_HAVE_ADDRESS: 'Dont have an address? ',
  EDIT_BUTTON_ADDRESS:'Edit',
  ADD_BUTTON_ADDRESS: 'Add',
  ADD_MORE_BUTTON_ADDRESS: 'Add More'
}